/**
 * Seed board: AI / business economy leaders (public trust from discourse).
 * Illustrative scores until trackers.py pipeline is live — always show SimulatedDataBadge.
 */
import type { RankedLeader, TrackerRow } from "@/lib/trackers-data";

function dims(partial: Record<string, number>) {
  return {
    trust: 50,
    leadership: 50,
    corruption: 50,
    economic_performance: 50,
    security_stability: 50,
    freedom_speech: 50,
    global_influence: 50,
    pragmatism_ideology: 50,
    youth_appeal: 50,
    transparency: 50,
    ...partial,
  };
}

/** Curated 15 — high-visibility AI / tech economy figures (not follower rank). */
export const AI_BUSINESS_LEADERS_SEED: RankedLeader[] = [
  {
    rank: 1,
    name: "Jensen Huang",
    flag: "🇹🇼",
    country: "United States",
    region: "Global",
    overall_score: 78,
    divergence: 34,
    summary: "Public discourse ties NVIDIA to the AI boom; trust high on competence, mixed on hype.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 76,
      leadership: 82,
      economic_performance: 88,
      transparency: 62,
      global_influence: 85,
      youth_appeal: 70,
    }),
  },
  {
    rank: 2,
    name: "Satya Nadella",
    flag: "🇮🇳",
    country: "United States",
    region: "Global",
    overall_score: 74,
    divergence: 28,
    summary: "Microsoft–OpenAI partnership dominates citizen talk; seen as steady institutional AI power.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 72,
      leadership: 75,
      economic_performance: 80,
      transparency: 68,
      global_influence: 78,
      pragmatism_ideology: 74,
    }),
  },
  {
    rank: 3,
    name: "Elon Musk",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 61,
    divergence: 72,
    summary: "Polarizing public trust: strong for free speech / xAI among supporters; sharp criticism elsewhere.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 52,
      leadership: 70,
      freedom_speech: 78,
      transparency: 48,
      youth_appeal: 65,
      global_influence: 90,
      pragmatism_ideology: 55,
    }),
  },
  {
    rank: 4,
    name: "Demis Hassabis",
    flag: "🇬🇧",
    country: "United Kingdom",
    region: "Europe",
    overall_score: 71,
    divergence: 22,
    summary: "DeepMind science narrative reads as high competence, lower consumer controversy.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 74,
      leadership: 70,
      economic_performance: 66,
      transparency: 70,
      global_influence: 68,
    }),
  },
  {
    rank: 5,
    name: "Sam Altman",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 58,
    divergence: 64,
    summary: "OpenAI visibility is huge; public trust swings with safety, board, and product stories.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 55,
      leadership: 68,
      transparency: 45,
      global_influence: 82,
      youth_appeal: 72,
    }),
  },
  {
    rank: 6,
    name: "Sundar Pichai",
    flag: "🇮🇳",
    country: "United States",
    region: "Global",
    overall_score: 63,
    divergence: 40,
    summary: "Google AI rollout talk mixes product excitement with antitrust and trust fatigue.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 60,
      leadership: 62,
      economic_performance: 75,
      transparency: 55,
      global_influence: 80,
    }),
  },
  {
    rank: 7,
    name: "Lisa Su",
    flag: "🇹🇼",
    country: "United States",
    region: "Americas",
    overall_score: 69,
    divergence: 25,
    summary: "AMD turnaround and AI chips earn quiet respect in tech discourse.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 71,
      leadership: 73,
      economic_performance: 74,
      transparency: 68,
      youth_appeal: 60,
    }),
  },
  {
    rank: 8,
    name: "Mark Zuckerberg",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 48,
    divergence: 70,
    summary: "Meta AI push competes with long-running trust and speech controversies.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 42,
      leadership: 58,
      freedom_speech: 40,
      transparency: 38,
      global_influence: 85,
      youth_appeal: 50,
    }),
  },
  {
    rank: 9,
    name: "Tim Cook",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 66,
    divergence: 30,
    summary: "Apple AI narrative is cautious; public trust tracks brand more than AI novelty.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 68,
      leadership: 65,
      economic_performance: 78,
      transparency: 60,
      global_influence: 76,
    }),
  },
  {
    rank: 10,
    name: "Dario Amodei",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 64,
    divergence: 35,
    summary: "Anthropic safety framing resonates with parts of public AI discourse.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 66,
      leadership: 62,
      transparency: 64,
      freedom_speech: 58,
      global_influence: 60,
    }),
  },
  {
    rank: 11,
    name: "Jeff Bezos",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 55,
    divergence: 55,
    summary: "Amazon / space / media power shapes trust more than pure AI products.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 50,
      leadership: 60,
      economic_performance: 72,
      transparency: 45,
      global_influence: 84,
    }),
  },
  {
    rank: 12,
    name: "Fei-Fei Li",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 70,
    divergence: 20,
    summary: "Research and human-centered AI voice; lower mass controversy than CEOs.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 75,
      leadership: 68,
      transparency: 72,
      youth_appeal: 65,
      global_influence: 58,
    }),
  },
  {
    rank: 13,
    name: "Yann LeCun",
    flag: "🇫🇷",
    country: "United States",
    region: "Europe",
    overall_score: 62,
    divergence: 45,
    summary: "Public AI debates (open vs closed, AGI timelines) drive polarized mentions.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 60,
      leadership: 58,
      freedom_speech: 70,
      transparency: 65,
      youth_appeal: 55,
    }),
  },
  {
    rank: 14,
    name: "Masayoshi Son",
    flag: "🇯🇵",
    country: "Japan",
    region: "Global",
    overall_score: 52,
    divergence: 50,
    summary: "SoftBank AI bets read as high-risk capital narrative in public talk.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 48,
      leadership: 55,
      economic_performance: 58,
      pragmatism_ideology: 45,
      global_influence: 70,
    }),
  },
  {
    rank: 15,
    name: "Mustafa Suleyman",
    flag: "🇬🇧",
    country: "United States",
    region: "Europe",
    overall_score: 60,
    divergence: 32,
    summary: "Microsoft AI leadership + prior Inflection story keeps him in economy discourse.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 62,
      leadership: 60,
      transparency: 58,
      global_influence: 64,
      youth_appeal: 58,
    }),
  },
];

export function seedAiBusinessTrackerRow(): TrackerRow {
  const global = AI_BUSINESS_LEADERS_SEED;
  const americas = global.filter((l) => l.region === "Americas" || l.country === "United States");
  const europe = global.filter((l) => l.region === "Europe");
  return {
    tracker_type: "ai_business_leader_trust",
    created_at: new Date().toISOString(),
    last_updated: new Date().toISOString(),
    item_count: global.length,
    snapshot_label: "seed-v1-illustrative",
    deep_dive_summary:
      "Illustrative citizen-trust ranking of AI / tech economy figures from public discourse patterns. Not live X samples yet — replace via trackers.py pipeline.",
    data: {
      regions: {
        americas,
        europe,
        middle_east: [],
        global: global.filter((l) => l.region === "Global"),
      },
      ranked_leaders: global,
    },
  };
}
