/**
 * Seed board: AI / business economy leaders (public trust from discourse).
 * Dimensions are interpreted via BUSINESS_LEADER_DIMENSIONS (Vision, Execution,
 * Free Speech Stance, etc.). Illustrative until trackers.py pipeline is live.
 */
import type { RankedLeader, TrackerRow } from "@/lib/trackers-data";

function dims(partial: Record<string, number>) {
  return {
    trust: 50,
    leadership: 50,
    corruption: 50,
    economic_performance: 50,
    security_stability: 50,
    freedom_speech: 50,
    global_influence: 50,
    pragmatism_ideology: 50,
    youth_appeal: 50,
    transparency: 50,
    ...partial,
  };
}

/**
 * Curated 15 — exclusive region tags (no overlap across buckets).
 * Elon Musk #1: free-speech course-change via X + AI/builder footprint.
 */
export const AI_BUSINESS_LEADERS_SEED: RankedLeader[] = [
  {
    rank: 1,
    name: "Elon Musk",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "xAI / Tesla / X",
    overall_score: 79,
    divergence: 74,
    summary:
      "Leads free-speech discourse after acquiring X and reversing prior moderation course; polarizing trust but unmatched speech + AI builder salience.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 58,
      leadership: 82, // Vision
      economic_performance: 78, // Execution
      freedom_speech: 96, // Free Speech Stance — category-defining
      transparency: 52,
      global_influence: 94, // Market Influence
      youth_appeal: 72, // Builder Appeal
      pragmatism_ideology: 70, // Innovation Pace
      security_stability: 55, // Safety & Governance
      corruption: 48, // Ethics Concern (lower = less concern in our scale used as score)
    }),
  },
  {
    rank: 2,
    name: "Jensen Huang",
    flag: "🇹🇼",
    country: "United States",
    region: "Americas",
    role: "NVIDIA",
    overall_score: 76,
    divergence: 32,
    summary: "Public discourse ties NVIDIA to the AI boom; highest competence/execution trust, quieter on speech politics.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 78,
      leadership: 84,
      economic_performance: 92,
      freedom_speech: 55,
      transparency: 64,
      global_influence: 88,
      youth_appeal: 74,
      pragmatism_ideology: 80,
      security_stability: 62,
      corruption: 70,
    }),
  },
  {
    rank: 3,
    name: "Satya Nadella",
    flag: "🇮🇳",
    country: "United States",
    region: "Americas",
    role: "Microsoft",
    overall_score: 72,
    divergence: 26,
    summary: "Microsoft–OpenAI partnership reads as steady institutional AI power; strong execution, moderate speech stance.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 74,
      leadership: 76,
      economic_performance: 82,
      freedom_speech: 52,
      transparency: 70,
      global_influence: 80,
      youth_appeal: 58,
      pragmatism_ideology: 72,
      security_stability: 68,
      corruption: 72,
    }),
  },
  {
    rank: 4,
    name: "Demis Hassabis",
    flag: "🇬🇧",
    country: "United Kingdom",
    region: "Europe",
    role: "Google DeepMind",
    overall_score: 70,
    divergence: 20,
    summary: "DeepMind science narrative: high competence, lower consumer controversy than consumer-AI CEOs.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 76,
      leadership: 72,
      economic_performance: 68,
      freedom_speech: 58,
      transparency: 72,
      global_influence: 70,
      youth_appeal: 60,
      pragmatism_ideology: 75,
      security_stability: 70,
      corruption: 74,
    }),
  },
  {
    rank: 5,
    name: "Lisa Su",
    flag: "🇹🇼",
    country: "United States",
    region: "Americas",
    role: "AMD",
    overall_score: 68,
    divergence: 24,
    summary: "AMD turnaround and AI accelerators earn quiet respect; strong execution without speech theater.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 72,
      leadership: 74,
      economic_performance: 76,
      freedom_speech: 54,
      transparency: 70,
      global_influence: 68,
      youth_appeal: 62,
      pragmatism_ideology: 73,
      security_stability: 65,
      corruption: 72,
    }),
  },
  {
    rank: 6,
    name: "Sam Altman",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "OpenAI",
    overall_score: 63,
    divergence: 66,
    summary: "Massive AI product visibility; trust swings with safety, board drama, and closed-model debates.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 56,
      leadership: 78,
      economic_performance: 74,
      freedom_speech: 48,
      transparency: 42,
      global_influence: 86,
      youth_appeal: 76,
      pragmatism_ideology: 68,
      security_stability: 58,
      corruption: 50,
    }),
  },
  {
    rank: 7,
    name: "Fei-Fei Li",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Stanford / AI research",
    overall_score: 67,
    divergence: 18,
    summary: "Human-centered AI research voice; high trust, lower mass controversy than platform CEOs.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 78,
      leadership: 70,
      economic_performance: 58,
      freedom_speech: 62,
      transparency: 76,
      global_influence: 60,
      youth_appeal: 68,
      pragmatism_ideology: 72,
      security_stability: 72,
      corruption: 78,
    }),
  },
  {
    rank: 8,
    name: "Dario Amodei",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Anthropic",
    overall_score: 65,
    divergence: 34,
    summary: "Anthropic safety framing resonates with parts of public AI discourse; cautious speech posture.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 68,
      leadership: 66,
      economic_performance: 64,
      freedom_speech: 50,
      transparency: 66,
      global_influence: 62,
      youth_appeal: 58,
      pragmatism_ideology: 60,
      security_stability: 78,
      corruption: 70,
    }),
  },
  {
    rank: 9,
    name: "Tim Cook",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Apple",
    overall_score: 64,
    divergence: 28,
    summary: "Apple Intelligence narrative is cautious; brand trust outruns AI novelty; privacy-forward speech posture.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 70,
      leadership: 66,
      economic_performance: 80,
      freedom_speech: 46,
      transparency: 58,
      global_influence: 78,
      youth_appeal: 55,
      pragmatism_ideology: 52,
      security_stability: 74,
      corruption: 68,
    }),
  },
  {
    rank: 10,
    name: "Sundar Pichai",
    flag: "🇮🇳",
    country: "United States",
    region: "Americas",
    role: "Google / Alphabet",
    overall_score: 60,
    divergence: 42,
    summary: "Google AI rollout mixes product excitement with antitrust, search trust fatigue, and moderation debates.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 55,
      leadership: 62,
      economic_performance: 76,
      freedom_speech: 38,
      transparency: 48,
      global_influence: 82,
      youth_appeal: 50,
      pragmatism_ideology: 55,
      security_stability: 60,
      corruption: 55,
    }),
  },
  {
    rank: 11,
    name: "Yann LeCun",
    flag: "🇫🇷",
    country: "United States",
    region: "Europe",
    role: "Meta AI / NYU",
    overall_score: 62,
    divergence: 44,
    summary: "Open-vs-closed and AGI-timeline debates; relatively strong open-science / speech lean vs closed labs.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 62,
      leadership: 60,
      economic_performance: 55,
      freedom_speech: 78,
      transparency: 70,
      global_influence: 64,
      youth_appeal: 58,
      pragmatism_ideology: 72,
      security_stability: 52,
      corruption: 68,
    }),
  },
  {
    rank: 12,
    name: "Mark Zuckerberg",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Meta",
    overall_score: 52,
    divergence: 68,
    summary: "Meta AI / Llama open-weight push competes with long-running trust and speech controversies.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 44,
      leadership: 64,
      economic_performance: 70,
      freedom_speech: 48,
      transparency: 40,
      global_influence: 86,
      youth_appeal: 52,
      pragmatism_ideology: 62,
      security_stability: 45,
      corruption: 42,
    }),
  },
  {
    rank: 13,
    name: "Mustafa Suleyman",
    flag: "🇬🇧",
    country: "United States",
    region: "Europe",
    role: "Microsoft AI",
    overall_score: 59,
    divergence: 30,
    summary: "Microsoft AI leadership + prior Inflection story; institutional builder narrative.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 60,
      leadership: 62,
      economic_performance: 64,
      freedom_speech: 50,
      transparency: 58,
      global_influence: 66,
      youth_appeal: 56,
      pragmatism_ideology: 64,
      security_stability: 66,
      corruption: 62,
    }),
  },
  {
    rank: 14,
    name: "Jeff Bezos",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Amazon / Blue Origin",
    overall_score: 54,
    divergence: 52,
    summary: "Amazon / space / media power shapes trust more than pure AI products; mixed speech via Washington Post ownership debates.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 48,
      leadership: 62,
      economic_performance: 74,
      freedom_speech: 42,
      transparency: 44,
      global_influence: 84,
      youth_appeal: 40,
      pragmatism_ideology: 58,
      security_stability: 55,
      corruption: 50,
    }),
  },
  {
    rank: 15,
    name: "Masayoshi Son",
    flag: "🇯🇵",
    country: "Japan",
    region: "Global",
    role: "SoftBank",
    overall_score: 50,
    divergence: 48,
    summary: "SoftBank AI bets read as high-risk capital narrative; influence via Vision Fund, uneven execution trust.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 46,
      leadership: 58,
      economic_performance: 52,
      freedom_speech: 45,
      transparency: 42,
      global_influence: 72,
      youth_appeal: 38,
      pragmatism_ideology: 48,
      security_stability: 50,
      corruption: 48,
    }),
  },
];

export function seedAiBusinessTrackerRow(): TrackerRow {
  // Sort by overall so ranked_leaders order matches scores (Musk first).
  const ranked = [...AI_BUSINESS_LEADERS_SEED].sort(
    (a, b) => (b.overall_score ?? 0) - (a.overall_score ?? 0),
  ).map((l, i) => ({ ...l, rank: i + 1 }));

  // Exclusive region buckets — no person in more than one (fixes duplicate rows).
  return {
    tracker_type: "ai_business_leader_trust",
    created_at: new Date().toISOString(),
    last_updated: new Date().toISOString(),
    item_count: ranked.length,
    snapshot_label: "seed-v2-speech-weighted-2026-08",
    deep_dive_summary:
      "Citizen-trust ranking of AI / tech economy figures. Free-speech stance weighted for platform owners who changed moderation course (notably X). Illustrative until live X pipeline.",
    data: {
      regions: {
        americas: ranked.filter((l) => l.region === "Americas"),
        europe: ranked.filter((l) => l.region === "Europe"),
        middle_east: ranked.filter((l) => l.region === "Middle East"),
        global: ranked.filter((l) => l.region === "Global"),
      },
      ranked_leaders: ranked,
    },
  };
}
