/**
 * Seed board: social awareness / citizen discourse figures & public voices.
 * Ranked by how public talk frames trust vs controversy — not an endorsement.
 * Illustrative until trackers.py pipeline is live.
 */
import type { RankedLeader, TrackerRow } from "@/lib/trackers-data";

function dims(partial: Record<string, number>) {
  return {
    trust: 50,
    leadership: 50,
    corruption: 50,
    economic_performance: 50,
    security_stability: 50,
    freedom_speech: 50,
    global_influence: 50,
    pragmatism_ideology: 50,
    youth_appeal: 50,
    transparency: 50,
    ...partial,
  };
}

/** 15 public discourse voices (migration, accountability, free speech, conflict, OSINT). */
export const CITIZEN_DISCOURSE_SEED: RankedLeader[] = [
  {
    rank: 1,
    name: "Matt Taibbi",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 64,
    divergence: 58,
    summary: "Institutional media trust and free-speech discourse; polarizing but high mention volume.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 62,
      transparency: 70,
      freedom_speech: 75,
      leadership: 55,
      youth_appeal: 48,
    }),
  },
  {
    rank: 2,
    name: "Michael Shellenberger",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 61,
    divergence: 60,
    summary: "Free speech / institutional critique narratives drive strong citizen engagement.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 58,
      freedom_speech: 72,
      transparency: 65,
      pragmatism_ideology: 60,
    }),
  },
  {
    rank: 3,
    name: "Glenn Greenwald",
    flag: "🇧🇷",
    country: "Brazil",
    region: "Americas",
    overall_score: 59,
    divergence: 62,
    summary: "Civil liberties framing; trust splits sharply by political camp.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 55,
      freedom_speech: 78,
      transparency: 68,
      global_influence: 60,
    }),
  },
  {
    rank: 4,
    name: "Bellingcat",
    flag: "🇳🇱",
    country: "Netherlands",
    region: "Europe",
    overall_score: 68,
    divergence: 40,
    summary: "OSINT accountability voice; often cited across camps for evidence trails.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 70,
      transparency: 75,
      leadership: 58,
      global_influence: 65,
      youth_appeal: 62,
    }),
  },
  {
    rank: 5,
    name: "Tim Pool",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 54,
    divergence: 66,
    summary: "Independent media reach is large; trust is polarized in public replies.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 50,
      freedom_speech: 70,
      youth_appeal: 58,
      transparency: 52,
    }),
  },
  {
    rank: 6,
    name: "Bill Melugin",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 57,
    divergence: 55,
    summary: "Border / migration on-the-ground reporting frequently surfaces in citizen talk.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 56,
      transparency: 60,
      security_stability: 58,
      leadership: 48,
    }),
  },
  {
    rank: 7,
    name: "Andy Ngo",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 45,
    divergence: 78,
    summary: "Street / crime reporting generates high engagement and high controversy.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 42,
      transparency: 50,
      security_stability: 55,
      freedom_speech: 60,
      youth_appeal: 40,
    }),
  },
  {
    rank: 8,
    name: "Lara Logan",
    flag: "🇿🇦",
    country: "United States",
    region: "Global",
    overall_score: 51,
    divergence: 65,
    summary: "Investigative / conflict narratives; public trust uneven across audiences.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 48,
      transparency: 55,
      leadership: 52,
      global_influence: 58,
    }),
  },
  {
    rank: 9,
    name: "Chris Rufo",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 49,
    divergence: 74,
    summary: "Institutional / culture discourse; strong mobilization, sharp counter-mobilization.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 45,
      leadership: 55,
      pragmatism_ideology: 42,
      youth_appeal: 50,
      freedom_speech: 58,
    }),
  },
  {
    rank: 10,
    name: "Nick Shirley",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    overall_score: 53,
    divergence: 50,
    summary: "Citizen video reporting style; trust tied to perceived on-the-ground authenticity.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 55,
      transparency: 58,
      youth_appeal: 68,
      leadership: 42,
    }),
  },
  {
    rank: 11,
    name: "Amnesty International",
    flag: "🇬🇧",
    country: "United Kingdom",
    region: "Europe",
    overall_score: 58,
    divergence: 48,
    summary: "NGO rights discourse; often the ‘official civil society’ frame citizens argue with.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 60,
      transparency: 55,
      global_influence: 70,
      pragmatism_ideology: 50,
    }),
  },
  {
    rank: 12,
    name: "Human Rights Watch",
    flag: "🇺🇸",
    country: "United States",
    region: "Global",
    overall_score: 56,
    divergence: 52,
    summary: "Institutional rights reporting; contested where geopolitics enter the feed.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 58,
      transparency: 54,
      global_influence: 72,
      leadership: 50,
    }),
  },
  {
    rank: 13,
    name: "IOM — UN Migration",
    flag: "🇨🇭",
    country: "Switzerland",
    region: "Europe",
    overall_score: 44,
    divergence: 70,
    summary: "Official migration framing vs citizen skepticism — useful gap signal, not popularity.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 40,
      transparency: 48,
      global_influence: 65,
      pragmatism_ideology: 45,
      security_stability: 42,
    }),
  },
  {
    rank: 14,
    name: "Benjamin Hall",
    flag: "🇬🇧",
    country: "United Kingdom",
    region: "Europe",
    overall_score: 63,
    divergence: 28,
    summary: "Conflict reporting resilience narrative; relatively less polarized than pundit accounts.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 66,
      leadership: 60,
      transparency: 62,
      global_influence: 55,
    }),
  },
  {
    rank: 15,
    name: "Hostages and Missing Families Forum",
    flag: "🇮🇱",
    country: "Israel",
    region: "Middle East",
    overall_score: 62,
    divergence: 55,
    summary: "Peace / hostage citizen advocacy discourse — high emotional salience in public feeds.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 65,
      transparency: 60,
      leadership: 52,
      global_influence: 58,
      pragmatism_ideology: 55,
    }),
  },
];

export function seedCitizenDiscourseTrackerRow(): TrackerRow {
  const scored = CITIZEN_DISCOURSE_SEED.filter((l) => l.status !== "waiting");
  const waiting = CITIZEN_DISCOURSE_SEED.filter((l) => l.status === "waiting");
  const global = [...scored, ...waiting];
  return {
    tracker_type: "citizen_discourse_index",
    created_at: new Date().toISOString(),
    last_updated: new Date().toISOString(),
    item_count: scored.length,
    snapshot_label: "seed-v1-illustrative",
    deep_dive_summary:
      "Illustrative ranking of public voices in social-awareness discourse (migration, accountability, free speech, conflict). Not an endorsement. Live X scoring comes later.",
    data: {
      regions: {
        americas: global.filter((l) => l.region === "Americas"),
        europe: global.filter((l) => l.region === "Europe"),
        middle_east: global.filter((l) => l.region === "Middle East"),
        global: global.filter((l) => l.region === "Global"),
      },
      ranked_leaders: global,
    },
  };
}
