/**
 * Seed board: individual citizen journalists / independent reporters.
 * NGOs, charities, and institutional orgs are excluded by design.
 * Dimensions use JOURNALIST_DIMENSIONS labels (Trust, Authenticity, Reporting Rigor, etc.).
 * Max 15 — high-visibility voices relevant to Elenchos (speech, accountability, on-the-ground).
 */
import type { RankedLeader, TrackerRow } from "@/lib/trackers-data";

function dims(partial: Record<string, number>) {
  return {
    trust: 50,
    leadership: 50, // Reporting Rigor
    corruption: 50, // Bias Concern
    economic_performance: 50, // Consistency
    security_stability: 50, // Courage / Risk
    freedom_speech: 50, // Independence
    global_influence: 50, // Reach of Conversation
    pragmatism_ideology: 50, // On-the-ground Focus
    youth_appeal: 50, // Citizen Resonance
    transparency: 50, // Authenticity
    ...partial,
  };
}

/** 15 individual accounts only — no NGOs / UN bodies / charities / forums. */
export const CITIZEN_DISCOURSE_SEED: RankedLeader[] = [
  {
    rank: 1,
    name: "Tucker Carlson",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Independent host",
    overall_score: 74,
    divergence: 78,
    summary:
      "Post-network independent platform; category-defining reach on speech, institutions, and foreign policy debates.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 58,
      transparency: 62,
      leadership: 70,
      freedom_speech: 88,
      global_influence: 92,
      youth_appeal: 68,
      pragmatism_ideology: 60,
      security_stability: 55,
      economic_performance: 78,
      corruption: 48,
    }),
  },
  {
    rank: 2,
    name: "Candace Owens",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Independent commentator",
    overall_score: 71,
    divergence: 80,
    summary:
      "High-reach independent voice; culture, speech, and institutional critique dominate citizen replies.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 55,
      transparency: 58,
      leadership: 66,
      freedom_speech: 84,
      global_influence: 86,
      youth_appeal: 72,
      pragmatism_ideology: 52,
      security_stability: 48,
      economic_performance: 74,
      corruption: 45,
    }),
  },
  {
    rank: 3,
    name: "Matt Taibbi",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Independent journalist",
    overall_score: 72,
    divergence: 56,
    summary: "Twitter Files / institutional media critique; high authenticity and independence in citizen talk.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 70,
      transparency: 78,
      leadership: 72,
      freedom_speech: 82,
      global_influence: 74,
      youth_appeal: 52,
      pragmatism_ideology: 68,
      security_stability: 55,
      economic_performance: 75,
      corruption: 62,
    }),
  },
  {
    rank: 4,
    name: "Megyn Kelly",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Independent host",
    overall_score: 68,
    divergence: 55,
    summary: "Ex-network → independent platform; speech / institutional critique with broad reach.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 62,
      transparency: 64,
      leadership: 66,
      freedom_speech: 76,
      global_influence: 78,
      youth_appeal: 52,
      pragmatism_ideology: 58,
      security_stability: 48,
      economic_performance: 74,
      corruption: 58,
    }),
  },
  {
    rank: 5,
    name: "Glenn Greenwald",
    flag: "🇧🇷",
    country: "Brazil",
    region: "Americas",
    role: "Independent journalist",
    overall_score: 68,
    divergence: 64,
    summary: "Civil liberties framing across camps; trust splits by audience, independence scores high.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 60,
      transparency: 74,
      leadership: 70,
      freedom_speech: 88,
      global_influence: 72,
      youth_appeal: 48,
      pragmatism_ideology: 62,
      security_stability: 60,
      economic_performance: 70,
      corruption: 58,
    }),
  },
  {
    rank: 6,
    name: "Michael Shellenberger",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Independent journalist",
    overall_score: 70,
    divergence: 58,
    summary: "Free speech / institutional critique; strong citizen engagement on censorship and crime narratives.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 66,
      transparency: 72,
      leadership: 68,
      freedom_speech: 80,
      global_influence: 70,
      youth_appeal: 55,
      pragmatism_ideology: 70,
      security_stability: 58,
      economic_performance: 72,
      corruption: 60,
    }),
  },
  {
    rank: 7,
    name: "Tim Pool",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Independent media",
    overall_score: 62,
    divergence: 68,
    summary: "Large independent reach; trust polarized; strong independence / speech framing.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 54,
      transparency: 58,
      leadership: 58,
      freedom_speech: 78,
      global_influence: 72,
      youth_appeal: 68,
      pragmatism_ideology: 60,
      security_stability: 50,
      economic_performance: 72,
      corruption: 48,
    }),
  },
  {
    rank: 8,
    name: "Bill Melugin",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Field reporter",
    overall_score: 67,
    divergence: 48,
    summary: "Border / migration on-the-ground reporting; authenticity tied to primary footage.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 68,
      transparency: 72,
      leadership: 70,
      freedom_speech: 65,
      global_influence: 62,
      youth_appeal: 58,
      pragmatism_ideology: 82,
      security_stability: 70,
      economic_performance: 74,
      corruption: 66,
    }),
  },
  {
    rank: 9,
    name: "Nick Shirley",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Citizen reporter",
    overall_score: 66,
    divergence: 46,
    summary: "Citizen video style; trust tied to perceived authenticity and youth reach.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 64,
      transparency: 76,
      leadership: 55,
      freedom_speech: 68,
      global_influence: 58,
      youth_appeal: 82,
      pragmatism_ideology: 80,
      security_stability: 62,
      economic_performance: 68,
      corruption: 64,
    }),
  },
  {
    rank: 10,
    name: "Benjamin Hall",
    flag: "🇬🇧",
    country: "United Kingdom",
    region: "Europe",
    role: "War correspondent",
    overall_score: 69,
    divergence: 26,
    summary: "Conflict reporting resilience; relatively less polarized than pundit accounts.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 74,
      transparency: 70,
      leadership: 76,
      freedom_speech: 62,
      global_influence: 64,
      youth_appeal: 50,
      pragmatism_ideology: 78,
      security_stability: 88,
      economic_performance: 72,
      corruption: 70,
    }),
  },
  {
    rank: 11,
    name: "Bari Weiss",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Independent publisher",
    overall_score: 64,
    divergence: 52,
    summary: "Ex-legacy → Free Press; institutional media critique and speech debates in citizen talk.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 62,
      transparency: 66,
      leadership: 68,
      freedom_speech: 74,
      global_influence: 70,
      youth_appeal: 48,
      pragmatism_ideology: 58,
      security_stability: 45,
      economic_performance: 70,
      corruption: 60,
    }),
  },
  {
    rank: 12,
    name: "Andy Ngo",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Street reporter",
    overall_score: 54,
    divergence: 78,
    summary: "Street / crime reporting; high engagement and high controversy; courage scores elevated.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 46,
      transparency: 58,
      leadership: 60,
      freedom_speech: 70,
      global_influence: 58,
      youth_appeal: 45,
      pragmatism_ideology: 75,
      security_stability: 82,
      economic_performance: 62,
      corruption: 44,
    }),
  },
  {
    rank: 13,
    name: "Lara Logan",
    flag: "🇿🇦",
    country: "United States",
    region: "Global",
    role: "Investigative journalist",
    overall_score: 56,
    divergence: 62,
    summary: "Investigative / conflict narratives; uneven trust across audiences, high risk profile.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 52,
      transparency: 60,
      leadership: 64,
      freedom_speech: 68,
      global_influence: 60,
      youth_appeal: 42,
      pragmatism_ideology: 66,
      security_stability: 78,
      economic_performance: 58,
      corruption: 50,
    }),
  },
  {
    rank: 14,
    name: "Alex Berenson",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Independent journalist",
    overall_score: 57,
    divergence: 70,
    summary: "Institutional skepticism beat; independence high, bias-concern scores contested by critics.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 54,
      transparency: 62,
      leadership: 58,
      freedom_speech: 78,
      global_influence: 55,
      youth_appeal: 48,
      pragmatism_ideology: 60,
      security_stability: 45,
      economic_performance: 65,
      corruption: 48,
    }),
  },
  {
    rank: 15,
    name: "James O'Keefe",
    flag: "🇺🇸",
    country: "United States",
    region: "Americas",
    role: "Undercover reporter",
    overall_score: 52,
    divergence: 76,
    summary: "Undercover / primary-video investigations; high courage and polarization in citizen replies.",
    posts_analyzed: 0,
    dimensions: dims({
      trust: 48,
      transparency: 58,
      leadership: 55,
      freedom_speech: 70,
      global_influence: 60,
      youth_appeal: 55,
      pragmatism_ideology: 72,
      security_stability: 80,
      economic_performance: 62,
      corruption: 42,
    }),
  },
];

export function seedCitizenDiscourseTrackerRow(): TrackerRow {
  const ranked = [...CITIZEN_DISCOURSE_SEED]
    .filter((l) => l.status !== "waiting")
    .sort((a, b) => (b.overall_score ?? 0) - (a.overall_score ?? 0))
    .map((l, i) => ({ ...l, rank: i + 1 }));

  return {
    tracker_type: "citizen_discourse_index",
    created_at: new Date().toISOString(),
    last_updated: new Date().toISOString(),
    item_count: ranked.length,
    snapshot_label: "seed-v3-top15-reach-2026-08",
    deep_dive_summary:
      "Top 15 individual citizen journalists / independent reporters by public discourse salience (speech, accountability, on-the-ground). NGOs and charities excluded. Illustrative until live X pipeline.",
    data: {
      regions: {
        americas: ranked.filter((l) => l.region === "Americas"),
        europe: ranked.filter((l) => l.region === "Europe"),
        middle_east: ranked.filter((l) => l.region === "Middle East"),
        global: ranked.filter((l) => l.region === "Global"),
      },
      ranked_leaders: ranked,
    },
  };
}
