/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as PeaceRouteImport } from './routes/peace'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResearchMigrationRouteImport } from './routes/research-migration'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SponsorRouteImport } from './routes/sponsor'
import { Route as AdminCurationRouteImport } from './routes/admin.curation'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'
import { Route as ResearchCommissionRouteImport } from './routes/research.commission'
import { Route as ResearchLibraryRouteImport } from './routes/research.library'
import { Route as SponsorSuccessRouteImport } from './routes/sponsor.success'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as TrackersIndexRouteImport } from './routes/trackers.index'
import { Route as TrackersFootballRouteImport } from './routes/trackers.football'
import { Route as TrackersLeadersRouteImport } from './routes/trackers.leaders'
import { Route as TrackersMediaRouteImport } from './routes/trackers.media'
import { Route as TrackersPeaceRouteImport } from './routes/trackers.peace'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiResearchCheckoutRouteImport } from './routes/api/research/checkout'
import { Route as ApiResearchFinalizeRouteImport } from './routes/api/research/finalize'
import { Route as ApiResearchWebhookRouteImport } from './routes/api/research/webhook'
import { Route as ResearchPreviewIndexRouteImport } from './routes/research.preview.index'
import { Route as ResearchPreviewSlugRouteImport } from './routes/research.preview.$slug'
import { Route as ResearchReportTokenRouteImport } from './routes/research.report.$token'
import { Route as ApiResearchReportTokenRouteImport } from './routes/api/research/report.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const PeaceRoute = PeaceRouteImport.update({
  id: '/peace',
  path: '/peace',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchMigrationRoute = ResearchMigrationRouteImport.update({
  id: '/research-migration',
  path: '/research-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/sponsor',
  path: '/sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurationRoute = AdminCurationRouteImport.update({
  id: '/admin/curation',
  path: '/admin/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchCommissionRoute = ResearchCommissionRouteImport.update({
  id: '/research/commission',
  path: '/research/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchLibraryRoute = ResearchLibraryRouteImport.update({
  id: '/research/library',
  path: '/research/library',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorSuccessRoute = SponsorSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => SponsorRoute,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersIndexRoute = TrackersIndexRouteImport.update({
  id: '/trackers/',
  path: '/trackers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersFootballRoute = TrackersFootballRouteImport.update({
  id: '/trackers/football',
  path: '/trackers/football',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersLeadersRoute = TrackersLeadersRouteImport.update({
  id: '/trackers/leaders',
  path: '/trackers/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersMediaRoute = TrackersMediaRouteImport.update({
  id: '/trackers/media',
  path: '/trackers/media',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersPeaceRoute = TrackersPeaceRouteImport.update({
  id: '/trackers/peace',
  path: '/trackers/peace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchCheckoutRoute = ApiResearchCheckoutRouteImport.update({
  id: '/api/research/checkout',
  path: '/api/research/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchFinalizeRoute = ApiResearchFinalizeRouteImport.update({
  id: '/api/research/finalize',
  path: '/api/research/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchWebhookRoute = ApiResearchWebhookRouteImport.update({
  id: '/api/research/webhook',
  path: '/api/research/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPreviewIndexRoute = ResearchPreviewIndexRouteImport.update({
  id: '/research/preview/',
  path: '/research/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPreviewSlugRoute = ResearchPreviewSlugRouteImport.update({
  id: '/research/preview/$slug',
  path: '/research/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchReportTokenRoute = ResearchReportTokenRouteImport.update({
  id: '/research/report/$token',
  path: '/research/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchReportTokenRoute = ApiResearchReportTokenRouteImport.update({
  id: '/api/research/report/$token',
  path: '/api/research/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaders': typeof LeadersRoute
  '/peace': typeof PeaceRoute
  '/privacy': typeof PrivacyRoute
  '/research-migration': typeof ResearchMigrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRouteWithChildren
  '/admin/curation': typeof AdminCurationRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/commission': typeof ResearchCommissionRoute
  '/research/library': typeof ResearchLibraryRoute
  '/sponsor/success': typeof SponsorSuccessRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/trackers/football': typeof TrackersFootballRoute
  '/trackers/leaders': typeof TrackersLeadersRoute
  '/trackers/media': typeof TrackersMediaRoute
  '/trackers/peace': typeof TrackersPeaceRoute
  '/research/': typeof ResearchIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/trackers/': typeof TrackersIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/research/checkout': typeof ApiResearchCheckoutRoute
  '/api/research/finalize': typeof ApiResearchFinalizeRoute
  '/api/research/webhook': typeof ApiResearchWebhookRoute
  '/research/preview/$slug': typeof ResearchPreviewSlugRoute
  '/research/report/$token': typeof ResearchReportTokenRoute
  '/research/preview/': typeof ResearchPreviewIndexRoute
  '/api/research/report/$token': typeof ApiResearchReportTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaders': typeof LeadersRoute
  '/peace': typeof PeaceRoute
  '/privacy': typeof PrivacyRoute
  '/research-migration': typeof ResearchMigrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRouteWithChildren
  '/admin/curation': typeof AdminCurationRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/commission': typeof ResearchCommissionRoute
  '/research/library': typeof ResearchLibraryRoute
  '/sponsor/success': typeof SponsorSuccessRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/trackers/football': typeof TrackersFootballRoute
  '/trackers/leaders': typeof TrackersLeadersRoute
  '/trackers/media': typeof TrackersMediaRoute
  '/trackers/peace': typeof TrackersPeaceRoute
  '/research': typeof ResearchIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/trackers': typeof TrackersIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/research/checkout': typeof ApiResearchCheckoutRoute
  '/api/research/finalize': typeof ApiResearchFinalizeRoute
  '/api/research/webhook': typeof ApiResearchWebhookRoute
  '/research/preview/$slug': typeof ResearchPreviewSlugRoute
  '/research/report/$token': typeof ResearchReportTokenRoute
  '/research/preview': typeof ResearchPreviewIndexRoute
  '/api/research/report/$token': typeof ApiResearchReportTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaders': typeof LeadersRoute
  '/peace': typeof PeaceRoute
  '/privacy': typeof PrivacyRoute
  '/research-migration': typeof ResearchMigrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sponsor': typeof SponsorRouteWithChildren
  '/admin/curation': typeof AdminCurationRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/commission': typeof ResearchCommissionRoute
  '/research/library': typeof ResearchLibraryRoute
  '/sponsor/success': typeof SponsorSuccessRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/trackers/football': typeof TrackersFootballRoute
  '/trackers/leaders': typeof TrackersLeadersRoute
  '/trackers/media': typeof TrackersMediaRoute
  '/trackers/peace': typeof TrackersPeaceRoute
  '/research/': typeof ResearchIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/trackers/': typeof TrackersIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/research/checkout': typeof ApiResearchCheckoutRoute
  '/api/research/finalize': typeof ApiResearchFinalizeRoute
  '/api/research/webhook': typeof ApiResearchWebhookRoute
  '/research/preview/$slug': typeof ResearchPreviewSlugRoute
  '/research/report/$token': typeof ResearchReportTokenRoute
  '/research/preview/': typeof ResearchPreviewIndexRoute
  '/api/research/report/$token': typeof ApiResearchReportTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/leaders'
    | '/peace'
    | '/privacy'
    | '/research-migration'
    | '/sitemap.xml'
    | '/sponsor'
    | '/admin/curation'
    | '/research/$slug'
    | '/research/commission'
    | '/research/library'
    | '/sponsor/success'
    | '/topics/$topicId'
    | '/trackers/football'
    | '/trackers/leaders'
    | '/trackers/media'
    | '/trackers/peace'
    | '/research/'
    | '/topics/'
    | '/trackers/'
    | '/api/public/contact'
    | '/api/research/checkout'
    | '/api/research/finalize'
    | '/api/research/webhook'
    | '/research/preview/$slug'
    | '/research/report/$token'
    | '/research/preview/'
    | '/api/research/report/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaders'
    | '/peace'
    | '/privacy'
    | '/research-migration'
    | '/sitemap.xml'
    | '/sponsor'
    | '/admin/curation'
    | '/research/$slug'
    | '/research/commission'
    | '/research/library'
    | '/sponsor/success'
    | '/topics/$topicId'
    | '/trackers/football'
    | '/trackers/leaders'
    | '/trackers/media'
    | '/trackers/peace'
    | '/research'
    | '/topics'
    | '/trackers'
    | '/api/public/contact'
    | '/api/research/checkout'
    | '/api/research/finalize'
    | '/api/research/webhook'
    | '/research/preview/$slug'
    | '/research/report/$token'
    | '/research/preview'
    | '/api/research/report/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/leaders'
    | '/peace'
    | '/privacy'
    | '/research-migration'
    | '/sitemap.xml'
    | '/sponsor'
    | '/admin/curation'
    | '/research/$slug'
    | '/research/commission'
    | '/research/library'
    | '/sponsor/success'
    | '/topics/$topicId'
    | '/trackers/football'
    | '/trackers/leaders'
    | '/trackers/media'
    | '/trackers/peace'
    | '/research/'
    | '/topics/'
    | '/trackers/'
    | '/api/public/contact'
    | '/api/research/checkout'
    | '/api/research/finalize'
    | '/api/research/webhook'
    | '/research/preview/$slug'
    | '/research/report/$token'
    | '/research/preview/'
    | '/api/research/report/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LeadersRoute: typeof LeadersRoute
  PeaceRoute: typeof PeaceRoute
  PrivacyRoute: typeof PrivacyRoute
  ResearchMigrationRoute: typeof ResearchMigrationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SponsorRoute: typeof SponsorRouteWithChildren
  AdminCurationRoute: typeof AdminCurationRoute
  ResearchSlugRoute: typeof ResearchSlugRoute
  ResearchCommissionRoute: typeof ResearchCommissionRoute
  ResearchLibraryRoute: typeof ResearchLibraryRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  TrackersFootballRoute: typeof TrackersFootballRoute
  TrackersLeadersRoute: typeof TrackersLeadersRoute
  TrackersMediaRoute: typeof TrackersMediaRoute
  TrackersPeaceRoute: typeof TrackersPeaceRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  TrackersIndexRoute: typeof TrackersIndexRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiResearchCheckoutRoute: typeof ApiResearchCheckoutRoute
  ApiResearchFinalizeRoute: typeof ApiResearchFinalizeRoute
  ApiResearchWebhookRoute: typeof ApiResearchWebhookRoute
  ResearchPreviewSlugRoute: typeof ResearchPreviewSlugRoute
  ResearchReportTokenRoute: typeof ResearchReportTokenRoute
  ResearchPreviewIndexRoute: typeof ResearchPreviewIndexRoute
  ApiResearchReportTokenRoute: typeof ApiResearchReportTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peace': {
      id: '/peace'
      path: '/peace'
      fullPath: '/peace'
      preLoaderRoute: typeof PeaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-migration': {
      id: '/research-migration'
      path: '/research-migration'
      fullPath: '/research-migration'
      preLoaderRoute: typeof ResearchMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor': {
      id: '/sponsor'
      path: '/sponsor'
      fullPath: '/sponsor'
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curation': {
      id: '/admin/curation'
      path: '/admin/curation'
      fullPath: '/admin/curation'
      preLoaderRoute: typeof AdminCurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/commission': {
      id: '/research/commission'
      path: '/research/commission'
      fullPath: '/research/commission'
      preLoaderRoute: typeof ResearchCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/library': {
      id: '/research/library'
      path: '/research/library'
      fullPath: '/research/library'
      preLoaderRoute: typeof ResearchLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsor/success': {
      id: '/sponsor/success'
      path: '/success'
      fullPath: '/sponsor/success'
      preLoaderRoute: typeof SponsorSuccessRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/': {
      id: '/trackers/'
      path: '/trackers'
      fullPath: '/trackers/'
      preLoaderRoute: typeof TrackersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/football': {
      id: '/trackers/football'
      path: '/trackers/football'
      fullPath: '/trackers/football'
      preLoaderRoute: typeof TrackersFootballRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/leaders': {
      id: '/trackers/leaders'
      path: '/trackers/leaders'
      fullPath: '/trackers/leaders'
      preLoaderRoute: typeof TrackersLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/media': {
      id: '/trackers/media'
      path: '/trackers/media'
      fullPath: '/trackers/media'
      preLoaderRoute: typeof TrackersMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/peace': {
      id: '/trackers/peace'
      path: '/trackers/peace'
      fullPath: '/trackers/peace'
      preLoaderRoute: typeof TrackersPeaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/checkout': {
      id: '/api/research/checkout'
      path: '/api/research/checkout'
      fullPath: '/api/research/checkout'
      preLoaderRoute: typeof ApiResearchCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/finalize': {
      id: '/api/research/finalize'
      path: '/api/research/finalize'
      fullPath: '/api/research/finalize'
      preLoaderRoute: typeof ApiResearchFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/webhook': {
      id: '/api/research/webhook'
      path: '/api/research/webhook'
      fullPath: '/api/research/webhook'
      preLoaderRoute: typeof ApiResearchWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/preview/': {
      id: '/research/preview/'
      path: '/research/preview'
      fullPath: '/research/preview/'
      preLoaderRoute: typeof ResearchPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/preview/$slug': {
      id: '/research/preview/$slug'
      path: '/research/preview/$slug'
      fullPath: '/research/preview/$slug'
      preLoaderRoute: typeof ResearchPreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/report/$token': {
      id: '/research/report/$token'
      path: '/research/report/$token'
      fullPath: '/research/report/$token'
      preLoaderRoute: typeof ResearchReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/report/$token': {
      id: '/api/research/report/$token'
      path: '/api/research/report/$token'
      fullPath: '/api/research/report/$token'
      preLoaderRoute: typeof ApiResearchReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SponsorRouteChildren {
  SponsorSuccessRoute: typeof SponsorSuccessRoute
}

const SponsorRouteChildren: SponsorRouteChildren = {
  SponsorSuccessRoute: SponsorSuccessRoute,
}

const SponsorRouteWithChildren =
  SponsorRoute._addFileChildren(SponsorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LeadersRoute: LeadersRoute,
  PeaceRoute: PeaceRoute,
  PrivacyRoute: PrivacyRoute,
  ResearchMigrationRoute: ResearchMigrationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SponsorRoute: SponsorRouteWithChildren,
  AdminCurationRoute: AdminCurationRoute,
  ResearchSlugRoute: ResearchSlugRoute,
  ResearchCommissionRoute: ResearchCommissionRoute,
  ResearchLibraryRoute: ResearchLibraryRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  TrackersFootballRoute: TrackersFootballRoute,
  TrackersLeadersRoute: TrackersLeadersRoute,
  TrackersMediaRoute: TrackersMediaRoute,
  TrackersPeaceRoute: TrackersPeaceRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  TrackersIndexRoute: TrackersIndexRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiResearchCheckoutRoute: ApiResearchCheckoutRoute,
  ApiResearchFinalizeRoute: ApiResearchFinalizeRoute,
  ApiResearchWebhookRoute: ApiResearchWebhookRoute,
  ResearchPreviewSlugRoute: ResearchPreviewSlugRoute,
  ResearchReportTokenRoute: ResearchReportTokenRoute,
  ResearchPreviewIndexRoute: ResearchPreviewIndexRoute,
  ApiResearchReportTokenRoute: ApiResearchReportTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
