/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as PeaceRouteImport } from './routes/peace'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProRouteImport } from './routes/pro'
import { Route as ResearchAviationRouteImport } from './routes/research-aviation'
import { Route as ResearchMigrationRouteImport } from './routes/research-migration'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AdminCurationRouteImport } from './routes/admin.curation'
import { Route as ResearchIndexRouteImport } from './routes/research.index'
import { Route as ResearchSlugRouteImport } from './routes/research.$slug'
import { Route as ResearchCommissionRouteImport } from './routes/research.commission'
import { Route as ResearchLibraryRouteImport } from './routes/research.library'
import { Route as ResearchNetworksLedgerRouteImport } from './routes/research.networks-ledger'
import { Route as ResearchSpeechReachRouteImport } from './routes/research.speech-reach'
import { Route as TopicsIndexRouteImport } from './routes/topics.index'
import { Route as TopicsTopicIdRouteImport } from './routes/topics.$topicId'
import { Route as TrackersIndexRouteImport } from './routes/trackers.index'
import { Route as TrackersBusinessRouteImport } from './routes/trackers.business'
import { Route as TrackersCitizenDiscourseRouteImport } from './routes/trackers.citizen-discourse'
import { Route as TrackersLeadersRouteImport } from './routes/trackers.leaders'
import { Route as TrackersPeaceRouteImport } from './routes/trackers.peace'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api/billing/checkout'
import { Route as ApiBillingMeRouteImport } from './routes/api/billing/me'
import { Route as ApiProRunRouteImport } from './routes/api/pro/run'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiResearchCheckoutRouteImport } from './routes/api/research/checkout'
import { Route as ApiResearchEmailRouteImport } from './routes/api/research/email'
import { Route as ApiResearchFinalizeRouteImport } from './routes/api/research/finalize'
import { Route as ApiResearchShareRouteImport } from './routes/api/research/share'
import { Route as ApiResearchSharedRouteImport } from './routes/api/research/shared'
import { Route as ApiResearchWebhookRouteImport } from './routes/api/research/webhook'
import { Route as ResearchNetworksLedgerSpeechReachRouteImport } from './routes/research.networks-ledger.speech-reach'
import { Route as ResearchPreviewIndexRouteImport } from './routes/research.preview.index'
import { Route as ResearchPreviewSlugRouteImport } from './routes/research.preview.$slug'
import { Route as ResearchReportTokenRouteImport } from './routes/research.report.$token'
import { Route as ApiResearchAdminCommissionRouteImport } from './routes/api/research/admin/commission'
import { Route as ApiResearchReportTokenRouteImport } from './routes/api/research/report.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const PeaceRoute = PeaceRouteImport.update({
  id: '/peace',
  path: '/peace',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchAviationRoute = ResearchAviationRouteImport.update({
  id: '/research-aviation',
  path: '/research-aviation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchMigrationRoute = ResearchMigrationRouteImport.update({
  id: '/research-migration',
  path: '/research-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCurationRoute = AdminCurationRouteImport.update({
  id: '/admin/curation',
  path: '/admin/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchIndexRoute = ResearchIndexRouteImport.update({
  id: '/research/',
  path: '/research/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSlugRoute = ResearchSlugRouteImport.update({
  id: '/research/$slug',
  path: '/research/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchCommissionRoute = ResearchCommissionRouteImport.update({
  id: '/research/commission',
  path: '/research/commission',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchLibraryRoute = ResearchLibraryRouteImport.update({
  id: '/research/library',
  path: '/research/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchNetworksLedgerRoute = ResearchNetworksLedgerRouteImport.update({
  id: '/research/networks-ledger',
  path: '/research/networks-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchSpeechReachRoute = ResearchSpeechReachRouteImport.update({
  id: '/research/speech-reach',
  path: '/research/speech-reach',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsIndexRoute = TopicsIndexRouteImport.update({
  id: '/topics/',
  path: '/topics/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopicsTopicIdRoute = TopicsTopicIdRouteImport.update({
  id: '/topics/$topicId',
  path: '/topics/$topicId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersIndexRoute = TrackersIndexRouteImport.update({
  id: '/trackers/',
  path: '/trackers/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersBusinessRoute = TrackersBusinessRouteImport.update({
  id: '/trackers/business',
  path: '/trackers/business',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersCitizenDiscourseRoute =
  TrackersCitizenDiscourseRouteImport.update({
    id: '/trackers/citizen-discourse',
    path: '/trackers/citizen-discourse',
    getParentRoute: () => rootRouteImport,
  } as any)
const TrackersLeadersRoute = TrackersLeadersRouteImport.update({
  id: '/trackers/leaders',
  path: '/trackers/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackersPeaceRoute = TrackersPeaceRouteImport.update({
  id: '/trackers/peace',
  path: '/trackers/peace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingMeRoute = ApiBillingMeRouteImport.update({
  id: '/api/billing/me',
  path: '/api/billing/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProRunRoute = ApiProRunRouteImport.update({
  id: '/api/pro/run',
  path: '/api/pro/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchCheckoutRoute = ApiResearchCheckoutRouteImport.update({
  id: '/api/research/checkout',
  path: '/api/research/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchEmailRoute = ApiResearchEmailRouteImport.update({
  id: '/api/research/email',
  path: '/api/research/email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchFinalizeRoute = ApiResearchFinalizeRouteImport.update({
  id: '/api/research/finalize',
  path: '/api/research/finalize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchShareRoute = ApiResearchShareRouteImport.update({
  id: '/api/research/share',
  path: '/api/research/share',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchSharedRoute = ApiResearchSharedRouteImport.update({
  id: '/api/research/shared',
  path: '/api/research/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchWebhookRoute = ApiResearchWebhookRouteImport.update({
  id: '/api/research/webhook',
  path: '/api/research/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchNetworksLedgerSpeechReachRoute =
  ResearchNetworksLedgerSpeechReachRouteImport.update({
    id: '/speech-reach',
    path: '/speech-reach',
    getParentRoute: () => ResearchNetworksLedgerRoute,
  } as any)
const ResearchPreviewIndexRoute = ResearchPreviewIndexRouteImport.update({
  id: '/research/preview/',
  path: '/research/preview/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchPreviewSlugRoute = ResearchPreviewSlugRouteImport.update({
  id: '/research/preview/$slug',
  path: '/research/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchReportTokenRoute = ResearchReportTokenRouteImport.update({
  id: '/research/report/$token',
  path: '/research/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResearchAdminCommissionRoute =
  ApiResearchAdminCommissionRouteImport.update({
    id: '/api/research/admin/commission',
    path: '/api/research/admin/commission',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiResearchReportTokenRoute = ApiResearchReportTokenRouteImport.update({
  id: '/api/research/report/$token',
  path: '/api/research/report/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaders': typeof LeadersRoute
  '/peace': typeof PeaceRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/research-aviation': typeof ResearchAviationRoute
  '/research-migration': typeof ResearchMigrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/curation': typeof AdminCurationRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/commission': typeof ResearchCommissionRoute
  '/research/library': typeof ResearchLibraryRoute
  '/research/networks-ledger': typeof ResearchNetworksLedgerRouteWithChildren
  '/research/speech-reach': typeof ResearchSpeechReachRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/trackers/business': typeof TrackersBusinessRoute
  '/trackers/citizen-discourse': typeof TrackersCitizenDiscourseRoute
  '/trackers/leaders': typeof TrackersLeadersRoute
  '/trackers/peace': typeof TrackersPeaceRoute
  '/research/': typeof ResearchIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/trackers/': typeof TrackersIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/me': typeof ApiBillingMeRoute
  '/api/pro/run': typeof ApiProRunRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/research/checkout': typeof ApiResearchCheckoutRoute
  '/api/research/email': typeof ApiResearchEmailRoute
  '/api/research/finalize': typeof ApiResearchFinalizeRoute
  '/api/research/share': typeof ApiResearchShareRoute
  '/api/research/shared': typeof ApiResearchSharedRoute
  '/api/research/webhook': typeof ApiResearchWebhookRoute
  '/research/networks-ledger/speech-reach': typeof ResearchNetworksLedgerSpeechReachRoute
  '/research/preview/$slug': typeof ResearchPreviewSlugRoute
  '/research/report/$token': typeof ResearchReportTokenRoute
  '/research/preview/': typeof ResearchPreviewIndexRoute
  '/api/research/admin/commission': typeof ApiResearchAdminCommissionRoute
  '/api/research/report/$token': typeof ApiResearchReportTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaders': typeof LeadersRoute
  '/peace': typeof PeaceRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/research-aviation': typeof ResearchAviationRoute
  '/research-migration': typeof ResearchMigrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/curation': typeof AdminCurationRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/commission': typeof ResearchCommissionRoute
  '/research/library': typeof ResearchLibraryRoute
  '/research/networks-ledger': typeof ResearchNetworksLedgerRouteWithChildren
  '/research/speech-reach': typeof ResearchSpeechReachRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/trackers/business': typeof TrackersBusinessRoute
  '/trackers/citizen-discourse': typeof TrackersCitizenDiscourseRoute
  '/trackers/leaders': typeof TrackersLeadersRoute
  '/trackers/peace': typeof TrackersPeaceRoute
  '/research': typeof ResearchIndexRoute
  '/topics': typeof TopicsIndexRoute
  '/trackers': typeof TrackersIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/me': typeof ApiBillingMeRoute
  '/api/pro/run': typeof ApiProRunRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/research/checkout': typeof ApiResearchCheckoutRoute
  '/api/research/email': typeof ApiResearchEmailRoute
  '/api/research/finalize': typeof ApiResearchFinalizeRoute
  '/api/research/share': typeof ApiResearchShareRoute
  '/api/research/shared': typeof ApiResearchSharedRoute
  '/api/research/webhook': typeof ApiResearchWebhookRoute
  '/research/networks-ledger/speech-reach': typeof ResearchNetworksLedgerSpeechReachRoute
  '/research/preview/$slug': typeof ResearchPreviewSlugRoute
  '/research/report/$token': typeof ResearchReportTokenRoute
  '/research/preview': typeof ResearchPreviewIndexRoute
  '/api/research/admin/commission': typeof ApiResearchAdminCommissionRoute
  '/api/research/report/$token': typeof ApiResearchReportTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/leaders': typeof LeadersRoute
  '/peace': typeof PeaceRoute
  '/privacy': typeof PrivacyRoute
  '/pro': typeof ProRoute
  '/research-aviation': typeof ResearchAviationRoute
  '/research-migration': typeof ResearchMigrationRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/curation': typeof AdminCurationRoute
  '/research/$slug': typeof ResearchSlugRoute
  '/research/commission': typeof ResearchCommissionRoute
  '/research/library': typeof ResearchLibraryRoute
  '/research/networks-ledger': typeof ResearchNetworksLedgerRouteWithChildren
  '/research/speech-reach': typeof ResearchSpeechReachRoute
  '/topics/$topicId': typeof TopicsTopicIdRoute
  '/trackers/business': typeof TrackersBusinessRoute
  '/trackers/citizen-discourse': typeof TrackersCitizenDiscourseRoute
  '/trackers/leaders': typeof TrackersLeadersRoute
  '/trackers/peace': typeof TrackersPeaceRoute
  '/research/': typeof ResearchIndexRoute
  '/topics/': typeof TopicsIndexRoute
  '/trackers/': typeof TrackersIndexRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/me': typeof ApiBillingMeRoute
  '/api/pro/run': typeof ApiProRunRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/research/checkout': typeof ApiResearchCheckoutRoute
  '/api/research/email': typeof ApiResearchEmailRoute
  '/api/research/finalize': typeof ApiResearchFinalizeRoute
  '/api/research/share': typeof ApiResearchShareRoute
  '/api/research/shared': typeof ApiResearchSharedRoute
  '/api/research/webhook': typeof ApiResearchWebhookRoute
  '/research/networks-ledger/speech-reach': typeof ResearchNetworksLedgerSpeechReachRoute
  '/research/preview/$slug': typeof ResearchPreviewSlugRoute
  '/research/report/$token': typeof ResearchReportTokenRoute
  '/research/preview/': typeof ResearchPreviewIndexRoute
  '/api/research/admin/commission': typeof ApiResearchAdminCommissionRoute
  '/api/research/report/$token': typeof ApiResearchReportTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/leaders'
    | '/peace'
    | '/privacy'
    | '/pro'
    | '/research-aviation'
    | '/research-migration'
    | '/sitemap.xml'
    | '/admin/curation'
    | '/research/$slug'
    | '/research/commission'
    | '/research/library'
    | '/research/networks-ledger'
    | '/research/speech-reach'
    | '/topics/$topicId'
    | '/trackers/business'
    | '/trackers/citizen-discourse'
    | '/trackers/leaders'
    | '/trackers/peace'
    | '/research/'
    | '/topics/'
    | '/trackers/'
    | '/api/billing/checkout'
    | '/api/billing/me'
    | '/api/pro/run'
    | '/api/public/contact'
    | '/api/research/checkout'
    | '/api/research/email'
    | '/api/research/finalize'
    | '/api/research/share'
    | '/api/research/shared'
    | '/api/research/webhook'
    | '/research/networks-ledger/speech-reach'
    | '/research/preview/$slug'
    | '/research/report/$token'
    | '/research/preview/'
    | '/api/research/admin/commission'
    | '/api/research/report/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/leaders'
    | '/peace'
    | '/privacy'
    | '/pro'
    | '/research-aviation'
    | '/research-migration'
    | '/sitemap.xml'
    | '/admin/curation'
    | '/research/$slug'
    | '/research/commission'
    | '/research/library'
    | '/research/networks-ledger'
    | '/research/speech-reach'
    | '/topics/$topicId'
    | '/trackers/business'
    | '/trackers/citizen-discourse'
    | '/trackers/leaders'
    | '/trackers/peace'
    | '/research'
    | '/topics'
    | '/trackers'
    | '/api/billing/checkout'
    | '/api/billing/me'
    | '/api/pro/run'
    | '/api/public/contact'
    | '/api/research/checkout'
    | '/api/research/email'
    | '/api/research/finalize'
    | '/api/research/share'
    | '/api/research/shared'
    | '/api/research/webhook'
    | '/research/networks-ledger/speech-reach'
    | '/research/preview/$slug'
    | '/research/report/$token'
    | '/research/preview'
    | '/api/research/admin/commission'
    | '/api/research/report/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/leaders'
    | '/peace'
    | '/privacy'
    | '/pro'
    | '/research-aviation'
    | '/research-migration'
    | '/sitemap.xml'
    | '/admin/curation'
    | '/research/$slug'
    | '/research/commission'
    | '/research/library'
    | '/research/networks-ledger'
    | '/research/speech-reach'
    | '/topics/$topicId'
    | '/trackers/business'
    | '/trackers/citizen-discourse'
    | '/trackers/leaders'
    | '/trackers/peace'
    | '/research/'
    | '/topics/'
    | '/trackers/'
    | '/api/billing/checkout'
    | '/api/billing/me'
    | '/api/pro/run'
    | '/api/public/contact'
    | '/api/research/checkout'
    | '/api/research/email'
    | '/api/research/finalize'
    | '/api/research/share'
    | '/api/research/shared'
    | '/api/research/webhook'
    | '/research/networks-ledger/speech-reach'
    | '/research/preview/$slug'
    | '/research/report/$token'
    | '/research/preview/'
    | '/api/research/admin/commission'
    | '/api/research/report/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LeadersRoute: typeof LeadersRoute
  PeaceRoute: typeof PeaceRoute
  PrivacyRoute: typeof PrivacyRoute
  ProRoute: typeof ProRoute
  ResearchAviationRoute: typeof ResearchAviationRoute
  ResearchMigrationRoute: typeof ResearchMigrationRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminCurationRoute: typeof AdminCurationRoute
  ResearchSlugRoute: typeof ResearchSlugRoute
  ResearchCommissionRoute: typeof ResearchCommissionRoute
  ResearchLibraryRoute: typeof ResearchLibraryRoute
  ResearchNetworksLedgerRoute: typeof ResearchNetworksLedgerRouteWithChildren
  ResearchSpeechReachRoute: typeof ResearchSpeechReachRoute
  TopicsTopicIdRoute: typeof TopicsTopicIdRoute
  TrackersBusinessRoute: typeof TrackersBusinessRoute
  TrackersCitizenDiscourseRoute: typeof TrackersCitizenDiscourseRoute
  TrackersLeadersRoute: typeof TrackersLeadersRoute
  TrackersPeaceRoute: typeof TrackersPeaceRoute
  ResearchIndexRoute: typeof ResearchIndexRoute
  TopicsIndexRoute: typeof TopicsIndexRoute
  TrackersIndexRoute: typeof TrackersIndexRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingMeRoute: typeof ApiBillingMeRoute
  ApiProRunRoute: typeof ApiProRunRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiResearchCheckoutRoute: typeof ApiResearchCheckoutRoute
  ApiResearchEmailRoute: typeof ApiResearchEmailRoute
  ApiResearchFinalizeRoute: typeof ApiResearchFinalizeRoute
  ApiResearchShareRoute: typeof ApiResearchShareRoute
  ApiResearchSharedRoute: typeof ApiResearchSharedRoute
  ApiResearchWebhookRoute: typeof ApiResearchWebhookRoute
  ResearchPreviewSlugRoute: typeof ResearchPreviewSlugRoute
  ResearchReportTokenRoute: typeof ResearchReportTokenRoute
  ResearchPreviewIndexRoute: typeof ResearchPreviewIndexRoute
  ApiResearchAdminCommissionRoute: typeof ApiResearchAdminCommissionRoute
  ApiResearchReportTokenRoute: typeof ApiResearchReportTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peace': {
      id: '/peace'
      path: '/peace'
      fullPath: '/peace'
      preLoaderRoute: typeof PeaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-aviation': {
      id: '/research-aviation'
      path: '/research-aviation'
      fullPath: '/research-aviation'
      preLoaderRoute: typeof ResearchAviationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research-migration': {
      id: '/research-migration'
      path: '/research-migration'
      fullPath: '/research-migration'
      preLoaderRoute: typeof ResearchMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/curation': {
      id: '/admin/curation'
      path: '/admin/curation'
      fullPath: '/admin/curation'
      preLoaderRoute: typeof AdminCurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/': {
      id: '/research/'
      path: '/research'
      fullPath: '/research/'
      preLoaderRoute: typeof ResearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/$slug': {
      id: '/research/$slug'
      path: '/research/$slug'
      fullPath: '/research/$slug'
      preLoaderRoute: typeof ResearchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/commission': {
      id: '/research/commission'
      path: '/research/commission'
      fullPath: '/research/commission'
      preLoaderRoute: typeof ResearchCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/library': {
      id: '/research/library'
      path: '/research/library'
      fullPath: '/research/library'
      preLoaderRoute: typeof ResearchLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/networks-ledger': {
      id: '/research/networks-ledger'
      path: '/research/networks-ledger'
      fullPath: '/research/networks-ledger'
      preLoaderRoute: typeof ResearchNetworksLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/speech-reach': {
      id: '/research/speech-reach'
      path: '/research/speech-reach'
      fullPath: '/research/speech-reach'
      preLoaderRoute: typeof ResearchSpeechReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/': {
      id: '/topics/'
      path: '/topics'
      fullPath: '/topics/'
      preLoaderRoute: typeof TopicsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topics/$topicId': {
      id: '/topics/$topicId'
      path: '/topics/$topicId'
      fullPath: '/topics/$topicId'
      preLoaderRoute: typeof TopicsTopicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/': {
      id: '/trackers/'
      path: '/trackers'
      fullPath: '/trackers/'
      preLoaderRoute: typeof TrackersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/business': {
      id: '/trackers/business'
      path: '/trackers/business'
      fullPath: '/trackers/business'
      preLoaderRoute: typeof TrackersBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/citizen-discourse': {
      id: '/trackers/citizen-discourse'
      path: '/trackers/citizen-discourse'
      fullPath: '/trackers/citizen-discourse'
      preLoaderRoute: typeof TrackersCitizenDiscourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/leaders': {
      id: '/trackers/leaders'
      path: '/trackers/leaders'
      fullPath: '/trackers/leaders'
      preLoaderRoute: typeof TrackersLeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trackers/peace': {
      id: '/trackers/peace'
      path: '/trackers/peace'
      fullPath: '/trackers/peace'
      preLoaderRoute: typeof TrackersPeaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/me': {
      id: '/api/billing/me'
      path: '/api/billing/me'
      fullPath: '/api/billing/me'
      preLoaderRoute: typeof ApiBillingMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pro/run': {
      id: '/api/pro/run'
      path: '/api/pro/run'
      fullPath: '/api/pro/run'
      preLoaderRoute: typeof ApiProRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/checkout': {
      id: '/api/research/checkout'
      path: '/api/research/checkout'
      fullPath: '/api/research/checkout'
      preLoaderRoute: typeof ApiResearchCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/email': {
      id: '/api/research/email'
      path: '/api/research/email'
      fullPath: '/api/research/email'
      preLoaderRoute: typeof ApiResearchEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/finalize': {
      id: '/api/research/finalize'
      path: '/api/research/finalize'
      fullPath: '/api/research/finalize'
      preLoaderRoute: typeof ApiResearchFinalizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/share': {
      id: '/api/research/share'
      path: '/api/research/share'
      fullPath: '/api/research/share'
      preLoaderRoute: typeof ApiResearchShareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/shared': {
      id: '/api/research/shared'
      path: '/api/research/shared'
      fullPath: '/api/research/shared'
      preLoaderRoute: typeof ApiResearchSharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/webhook': {
      id: '/api/research/webhook'
      path: '/api/research/webhook'
      fullPath: '/api/research/webhook'
      preLoaderRoute: typeof ApiResearchWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/networks-ledger/speech-reach': {
      id: '/research/networks-ledger/speech-reach'
      path: '/speech-reach'
      fullPath: '/research/networks-ledger/speech-reach'
      preLoaderRoute: typeof ResearchNetworksLedgerSpeechReachRouteImport
      parentRoute: typeof ResearchNetworksLedgerRoute
    }
    '/research/preview/': {
      id: '/research/preview/'
      path: '/research/preview'
      fullPath: '/research/preview/'
      preLoaderRoute: typeof ResearchPreviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/preview/$slug': {
      id: '/research/preview/$slug'
      path: '/research/preview/$slug'
      fullPath: '/research/preview/$slug'
      preLoaderRoute: typeof ResearchPreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research/report/$token': {
      id: '/research/report/$token'
      path: '/research/report/$token'
      fullPath: '/research/report/$token'
      preLoaderRoute: typeof ResearchReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/admin/commission': {
      id: '/api/research/admin/commission'
      path: '/api/research/admin/commission'
      fullPath: '/api/research/admin/commission'
      preLoaderRoute: typeof ApiResearchAdminCommissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/research/report/$token': {
      id: '/api/research/report/$token'
      path: '/api/research/report/$token'
      fullPath: '/api/research/report/$token'
      preLoaderRoute: typeof ApiResearchReportTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ResearchNetworksLedgerRouteChildren {
  ResearchNetworksLedgerSpeechReachRoute: typeof ResearchNetworksLedgerSpeechReachRoute
}

const ResearchNetworksLedgerRouteChildren: ResearchNetworksLedgerRouteChildren =
  {
    ResearchNetworksLedgerSpeechReachRoute:
      ResearchNetworksLedgerSpeechReachRoute,
  }

const ResearchNetworksLedgerRouteWithChildren =
  ResearchNetworksLedgerRoute._addFileChildren(
    ResearchNetworksLedgerRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LeadersRoute: LeadersRoute,
  PeaceRoute: PeaceRoute,
  PrivacyRoute: PrivacyRoute,
  ProRoute: ProRoute,
  ResearchAviationRoute: ResearchAviationRoute,
  ResearchMigrationRoute: ResearchMigrationRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminCurationRoute: AdminCurationRoute,
  ResearchSlugRoute: ResearchSlugRoute,
  ResearchCommissionRoute: ResearchCommissionRoute,
  ResearchLibraryRoute: ResearchLibraryRoute,
  ResearchNetworksLedgerRoute: ResearchNetworksLedgerRouteWithChildren,
  ResearchSpeechReachRoute: ResearchSpeechReachRoute,
  TopicsTopicIdRoute: TopicsTopicIdRoute,
  TrackersBusinessRoute: TrackersBusinessRoute,
  TrackersCitizenDiscourseRoute: TrackersCitizenDiscourseRoute,
  TrackersLeadersRoute: TrackersLeadersRoute,
  TrackersPeaceRoute: TrackersPeaceRoute,
  ResearchIndexRoute: ResearchIndexRoute,
  TopicsIndexRoute: TopicsIndexRoute,
  TrackersIndexRoute: TrackersIndexRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingMeRoute: ApiBillingMeRoute,
  ApiProRunRoute: ApiProRunRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiResearchCheckoutRoute: ApiResearchCheckoutRoute,
  ApiResearchEmailRoute: ApiResearchEmailRoute,
  ApiResearchFinalizeRoute: ApiResearchFinalizeRoute,
  ApiResearchShareRoute: ApiResearchShareRoute,
  ApiResearchSharedRoute: ApiResearchSharedRoute,
  ApiResearchWebhookRoute: ApiResearchWebhookRoute,
  ResearchPreviewSlugRoute: ResearchPreviewSlugRoute,
  ResearchReportTokenRoute: ResearchReportTokenRoute,
  ResearchPreviewIndexRoute: ResearchPreviewIndexRoute,
  ApiResearchAdminCommissionRoute: ApiResearchAdminCommissionRoute,
  ApiResearchReportTokenRoute: ApiResearchReportTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
